/**
 * AI Market Events Generator
 * --------------------------------------------------------------------------
 * Acts as a background "financial news simulator". Every cycle it produces a
 * breaking-news headline plus a sentiment score from -10 (crash) to +10
 * (rally). The score is fed into the SpacetimeDB `apply_market_shock` reducer,
 * which swings live market prices for every connected trader.
 *
 * Security note: NO LLM API keys exist in this bundle. Ambient market events
 * are generated by the offline simulator below (labeled `simulated`), and the
 * player-driven "Remix" feature is parsed server-side via /api/remix (Gemini
 * key stays in the serverless environment), with a local keyword parser as
 * the keyless fallback. Ambient events deliberately do NOT call the LLM:
 * every connected client firing a Gemini request each minute would be both a
 * quota burner and pointless — the simulator drives the same server reducer.
 */

export interface MarketEvent {
  headline: string;
  sentiment: number; // -10 .. +10
  source: 'simulated';
}

const TICKERS = ['AAPL', 'NVDA', 'TSLA', 'BTC', 'MSFT', 'GOOG', 'JPM', 'V'];

// Templated headlines grouped by sentiment band. {T} is replaced with a ticker.
const BULLISH = [
  '{T} smashes earnings, guidance raised across the board',
  'Fed signals surprise rate cut — risk assets rip higher',
  '{T} unveils blockbuster AI chip, orders backlogged for years',
  'Institutional whales pile into {T}, volume hits record',
  'Breakthrough product launch sends {T} to all-time highs',
  'Short squeeze ignites as {T} bears capitulate',
];
const BEARISH = [
  'SEC opens formal probe into {T} accounting practices',
  '{T} misses badly, slashes full-year outlook',
  'Liquidity crunch spooks markets — {T} leads the selloff',
  'Surprise hot inflation print hammers growth names like {T}',
  'Regulators threaten antitrust breakup of {T}',
  'Flash crash: {T} circuit breakers triggered on heavy selling',
];
const NEUTRAL = [
  '{T} trades flat as traders await CPI data',
  'Mixed signals: {T} options imply elevated volatility',
  'Analysts split on {T} after sideways quarter',
  'Markets digest {T} headlines, awaiting next catalyst',
];

const pick = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
const randTicker = () => pick(TICKERS);

export function simulatedEvent(rng: () => number = Math.random): MarketEvent {
  // Bias slightly toward action (non-neutral) so the market keeps moving.
  const roll = rng();
  let band: string[];
  let sentiment: number;
  if (roll < 0.42) {
    band = BULLISH;
    sentiment = 4 + Math.floor(rng() * 7); // +4 .. +10
  } else if (roll < 0.84) {
    band = BEARISH;
    sentiment = -(4 + Math.floor(rng() * 7)); // -4 .. -10
  } else {
    band = NEUTRAL;
    sentiment = Math.floor(rng() * 5) - 2; // -2 .. +2
  }
  const headline = band[Math.floor(rng() * band.length)].replace('{T}', randTicker());
  return { headline, sentiment, source: 'simulated' };
}

export async function generateMarketEvent(): Promise<MarketEvent> {
  return simulatedEvent();
}

// ===========================================================================
// PROMPT-TO-GAME "REMIX" ENGINE
// Parses a player's natural-language prompt into structured market parameters
// that drive the SpacetimeDB `remix_market` reducer. Tries the server-side
// Gemini proxy first, otherwise a robust local keyword parser (so keyless
// local dev always works).
// ===========================================================================

export interface RemixParams {
  ticker: string; // specific symbol or "ALL"
  driftModifier: number; // -0.5 .. 0.5 (trend + instant jolt)
  volatilityModifier: number; // -0.5 .. 0.8 (turbulence)
  headline: string;
  source: 'gemini' | 'parsed';
}

const TICKER_KEYWORDS: Record<string, string[]> = {
  AAPL: ['apple', 'aapl', 'iphone'],
  NVDA: ['nvidia', 'nvda', 'gpu', 'chip', 'ai chip', 'semiconductor'],
  TSLA: ['tesla', 'tsla', 'ev', 'electric vehicle', 'musk'],
  BTC: ['bitcoin', 'btc', 'crypto', 'cryptocurrency'],
  MSFT: ['microsoft', 'msft', 'azure'],
  GOOG: ['google', 'goog', 'alphabet', 'search'],
  JPM: ['jpmorgan', 'jpm', 'bank', 'banking', 'financials'],
  V: ['visa', 'payments', 'card'],
};

const POSITIVE_WORDS = ['rally', 'surge', 'squeeze', 'short squeeze', 'boom', 'soar', 'moon', 'bullish', 'breakthrough', 'pump', 'spike up', 'rip', 'melt up', 'green'];
const NEGATIVE_WORDS = ['crash', 'plunge', 'collapse', 'sell-off', 'selloff', 'recession', 'crisis', 'probe', 'fraud', 'ban', 'bearish', 'dump', 'tank', 'meltdown', 'red', 'panic', 'default'];
const VOLATILE_WORDS = ['volatility', 'volatile', 'chaos', 'swing', 'turbulence', 'turbulent', 'wild', 'uncertainty', 'whipsaw', 'supply chain'];

function clamp(n: number, lo: number, hi: number) {
  return Math.max(lo, Math.min(hi, n));
}

export function localParseRemix(prompt: string): RemixParams {
  const p = prompt.toLowerCase();

  // Detect ticker (sector keywords too). Default to whole market.
  let ticker = 'ALL';
  for (const [sym, words] of Object.entries(TICKER_KEYWORDS)) {
    if (words.some((w) => p.includes(w))) { ticker = sym; break; }
  }
  if (p.includes('tech') && ticker === 'ALL') ticker = 'NVDA';

  // Sentiment direction + intensity.
  const posHits = POSITIVE_WORDS.filter((w) => p.includes(w)).length;
  const negHits = NEGATIVE_WORDS.filter((w) => p.includes(w)).length;
  const volHits = VOLATILE_WORDS.filter((w) => p.includes(w)).length;

  let drift = 0;
  if (posHits > negHits) drift = clamp(0.12 + posHits * 0.05, 0.1, 0.3);
  else if (negHits > posHits) drift = clamp(-(0.12 + negHits * 0.05), -0.3, -0.1);
  else drift = 0;

  // Intensifiers.
  if (/\b(massive|huge|global|severe|extreme|violent)\b/.test(p)) {
    drift = clamp(drift * 1.5, -0.4, 0.4);
  }

  const volatility = clamp(0.12 + volHits * 0.18 + Math.abs(drift) * 0.4, 0.08, 0.6);

  const dir = drift > 0.02 ? '📈' : drift < -0.02 ? '📉' : '◆';
  const scope = ticker === 'ALL' ? 'markets' : ticker;
  const headline = `${dir} REMIX: ${prompt.trim().slice(0, 90)} — ${scope} react`;

  return { ticker, driftModifier: Number(drift.toFixed(3)), volatilityModifier: Number(volatility.toFixed(3)), headline, source: 'parsed' };
}

/** Ask the server-side Gemini proxy to parse the prompt. Null on any failure. */
async function remixFromProxy(prompt: string): Promise<RemixParams | null> {
  try {
    const res = await fetch('/api/remix', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt }),
    });
    if (!res.ok) return null;
    const obj = (await res.json()) as Partial<RemixParams>;
    if (typeof obj.ticker !== 'string' || typeof obj.headline !== 'string') return null;
    return {
      ticker: obj.ticker.toUpperCase(),
      driftModifier: clamp(Number(obj.driftModifier) || 0, -0.5, 0.5),
      volatilityModifier: clamp(Number(obj.volatilityModifier) || 0, -0.5, 0.8),
      headline: obj.headline.slice(0, 120),
      source: 'gemini',
    };
  } catch {
    return null;
  }
}

export async function parseRemixPrompt(prompt: string): Promise<RemixParams> {
  const viaProxy = await remixFromProxy(prompt);
  if (viaProxy) return viaProxy;
  return localParseRemix(prompt);
}
