import React from 'react';
import { MarketNews } from '../generated/types';

interface NewsTickerProps {
  news: MarketNews[];
  regime?: number; // sim_math::Regime as u8 (0 calm, 1 volatile, 2 crisis)
  onRegimeClick?: () => void;
}

const sentimentClass = (s: number) => (s >= 3 ? 'bull' : s <= -3 ? 'bear' : 'neutral');
const sentimentArrow = (s: number) => (s >= 3 ? '▲' : s <= -3 ? '▼' : '◆');

// Active market-volatility regime (server-driven, see sim_math::Regime).
const REGIMES = [
  { label: 'CALM', cls: 'bull' },
  { label: 'VOLATILE', cls: 'neutral' },
  { label: 'CRISIS', cls: 'bear' },
] as const;

export const NewsTicker: React.FC<NewsTickerProps> = ({ news, regime = 0, onRegimeClick }) => {
  const sorted = [...news].sort((a, b) => Number(b.newsId) - Number(a.newsId));
  const latest = sorted[0];
  const activeRegime = REGIMES[regime] ?? REGIMES[0];

  return (
    <div className="newsticker">
      <div className="newsticker-badge" title="Headlines are generated by the simulation, not a real news feed">
        <span className="newsticker-ai">SIM</span>
        <span className="newsticker-label">MARKET WIRE</span>
      </div>
      <button
        type="button"
        className={`newsticker-regime ${activeRegime.cls}`}
        title="Active market volatility regime — click to see how the market is modelled"
        onClick={onRegimeClick}
      >
        <span className="newsticker-regime-dot" />
        {activeRegime.label}
      </button>
      <div className="newsticker-scroll">
        {sorted.length === 0 ? (
          <span className="newsticker-item neutral">◆ AI market simulator online — awaiting first headline…</span>
        ) : (
          <div className="newsticker-track">
            {sorted.concat(sorted).map((n, i) => (
              <span key={`${n.newsId.toString()}-${i}`} className={`newsticker-item ${sentimentClass(n.sentiment)}`}>
                {sentimentArrow(n.sentiment)} {n.headline}
                <span className="newsticker-score">[{n.sentiment > 0 ? '+' : ''}{n.sentiment}]</span>
              </span>
            ))}
          </div>
        )}
      </div>
      {latest && (
        <div className={`newsticker-flash ${sentimentClass(latest.sentiment)}`} key={latest.newsId.toString()} />
      )}
    </div>
  );
};
